apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/eshaul-work/image-rec
    jibMaven: {}
deploy:
  kubectl:
    manifests:
      - k8s/web.yaml

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
