apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/eshaul-work/image-rec
    jibMaven: {}

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
